<a href="https://colab.research.google.com/github/Suryan5h/Deep-Learning/blob/main/Auto_gradient_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
p = tf.Variable([[1,2,3,4], [6,7,8,9], [1,2,3,4], [6,7,8,9]])
r = tf.Variable([[100], [10], [100], [10]])
q=p*r
print(q)

tf.Tensor(
[[100 200 300 400]
 [ 60  70  80  90]
 [100 200 300 400]
 [ 60  70  80  90]], shape=(4, 4), dtype=int32)


In [3]:
p = tf.Variable([[1,2,3,4], [6,7,8,9], [1,2,3,4], [6,7,8,9]])
r = tf.Variable([[100, 10, 100, 10]])
q=p*r
print(q)

tf.Tensor(
[[100  20 300  40]
 [600  70 800  90]
 [100  20 300  40]
 [600  70 800  90]], shape=(4, 4), dtype=int32)


In [9]:
t = tf.Variable(0.5)
pi = tf.constant(3.14)
with tf.GradientTape() as tape:
  r=t**2
  theta = t-pi
  S = 3*r*tf.math.cos(theta)

dS_dt = tape.gradient(S,t)
print(dS_dt.numpy())

-2.269837
