<a href="https://colab.research.google.com/github/Suryan5h/Deep-Learning/blob/main/Declaring_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Declaring tensors

In [2]:
import tensorflow as tf
import numpy as np

In [8]:
# approach 1 - initialize the nd array in numpy and then use that to initialize the tensor
arr = np.random.randn(2,2,2,2) # returns random numbers from standard normal distribution-> mean=0 and std_dev = 1
print(arr.shape)
print(arr)

#to change the mean to 1
arr= arr+1

# to change std dev (for eg. std to 2.5 and mean=1)
# arr = 2.5 * arr + 1

arr_tf = tf.constant(arr)
print(arr_tf)

(2, 2, 2, 2)
[[[[-1.08794193  1.72940536]
   [ 1.06267729  0.18409602]]

  [[-0.18225608  0.5889786 ]
   [ 0.41146245 -1.11360789]]]


 [[[ 0.46052027  0.151689  ]
   [ 0.96723423 -0.12782456]]

  [[ 1.5465438   1.71291856]
   [-1.85950547 -0.32300577]]]]
tf.Tensor(
[[[[-0.08794193  2.72940536]
   [ 2.06267729  1.18409602]]

  [[ 0.81774392  1.5889786 ]
   [ 1.41146245 -0.11360789]]]


 [[[ 1.46052027  1.151689  ]
   [ 1.96723423  0.87217544]]

  [[ 2.5465438   2.71291856]
   [-0.85950547  0.67699423]]]], shape=(2, 2, 2, 2), dtype=float64)


In [7]:
# convert to numpy array
print(type(arr_tf.numpy()))

<class 'numpy.ndarray'>


In [9]:
# approach 2 - using random number generating functions from TensorFlow
arr_tf = tf.random.normal((2,2,2,2), mean=1,stddev=1,name="my_tensor")
print(arr_tf.shape)
print(arr_tf.numpy())

(2, 2, 2, 2)
[[[[ 0.5288888   0.7821159 ]
   [ 1.668256    1.8159883 ]]

  [[-1.2573655   0.38415825]
   [ 0.17854476  0.29505938]]]


 [[[ 1.5150928   0.84227043]
   [-0.832652    0.500628  ]]

  [[ 0.4974625   2.2983122 ]
   [ 0.03249741  2.0833216 ]]]]


In [10]:
print(arr_tf)

tf.Tensor(
[[[[ 0.5288888   0.7821159 ]
   [ 1.668256    1.8159883 ]]

  [[-1.2573655   0.38415825]
   [ 0.17854476  0.29505938]]]


 [[[ 1.5150928   0.84227043]
   [-0.832652    0.500628  ]]

  [[ 0.4974625   2.2983122 ]
   [ 0.03249741  2.0833216 ]]]], shape=(2, 2, 2, 2), dtype=float32)


In [11]:
arr_tf

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[ 0.5288888 ,  0.7821159 ],
         [ 1.668256  ,  1.8159883 ]],

        [[-1.2573655 ,  0.38415825],
         [ 0.17854476,  0.29505938]]],


       [[[ 1.5150928 ,  0.84227043],
         [-0.832652  ,  0.500628  ]],

        [[ 0.4974625 ,  2.2983122 ],
         [ 0.03249741,  2.0833216 ]]]], dtype=float32)>

In [12]:
arr_tf.numpy()

array([[[[ 0.5288888 ,  0.7821159 ],
         [ 1.668256  ,  1.8159883 ]],

        [[-1.2573655 ,  0.38415825],
         [ 0.17854476,  0.29505938]]],


       [[[ 1.5150928 ,  0.84227043],
         [-0.832652  ,  0.500628  ]],

        [[ 0.4974625 ,  2.2983122 ],
         [ 0.03249741,  2.0833216 ]]]], dtype=float32)

In [14]:
tensor1 = tf.random.uniform((2,2), minval= 1, maxval= 20, dtype= tf.int32)
print("Initial tensor: ", tensor1.numpy())
tensor2 = tf.pow(tensor1, 2)
print("Squared tensor = ", tensor2.numpy())

Initial tensor:  [[1 7]
 [5 6]]
Squared tensor =  [[ 1 49]
 [25 36]]


In [15]:
tensor1 = tf.random.uniform((2,2), minval= 1, maxval= 20)
print("Initial tensor: ", tensor1.numpy())
tensor2 = tf.pow(tensor1, 2)
print("Squared tensor = ", tensor2.numpy())

Initial tensor:  [[ 9.833239 11.277818]
 [ 9.646095 17.53631 ]]
Squared tensor =  [[ 96.69258 127.18917]
 [ 93.04716 307.5222 ]]


In [16]:
tensor1 = tf.random.uniform((2,2), minval= 1, maxval= 20, dtype= tf.int32)
print("Initial tensor: ", tensor1.numpy())
tensor2 = tensor1 * tensor1
print("Squared tensor = ", tensor2.numpy())

Initial tensor:  [[19 15]
 [ 6 17]]
Squared tensor =  [[361 225]
 [ 36 289]]


In [17]:

tensor1 = tf.random.uniform((2,2), minval= 1, maxval= 20, dtype= tf.int32)
print("Initial tensor: ", tensor1.numpy())
tensor2 = tf.multiply( tensor1 , tensor1)
print("Squared tensor = ", tensor2.numpy())

Initial tensor:  [[11 19]
 [15  8]]
Squared tensor =  [[121 361]
 [225  64]]


In [19]:
t1 = tf.Variable([[2,3,4], [5,7,9], [1,6,3], [5,8,4]])
t2 = tf.Variable([[2,3,4,5], [5,7,9,4], [1,6,3,9]])

# t3 = t1 + t2
# error throw as dimensions are not same.

In [20]:
# Solve the following system of linear equations using TensorFlow. 

# x + y + z + w = 13
# 2x + 3y − w = −1
# −3x + 4y + z + 2w = 10
# x + 2y − z + w = 1

# Answer: x=2, y=0, z=6 and w=5

In [33]:
x = tf.constant([[1,1,1,1],
                 [2,3,0,-1],
                 [-3,4,1,2],
                 [1,2,-1,1]],dtype='float')

y = tf.constant([[13],[-1],[10],[1]],dtype='float')
xinv = tf.linalg.inv(x)
ny = y
ans = tf.linalg.matmul(xinv,y)
print(ans)

tf.Tensor(
[[ 2.0000000e+00]
 [-1.0058284e-07]
 [ 5.9999995e+00]
 [ 5.0000005e+00]], shape=(4, 1), dtype=float32)


In [42]:
# Question
# Using logistic regression - means using sigmoid function find the prob. of positive class
weights = tf.constant([[0.5,1,-1.2]],dtype='float')
features = tf.constant([[0.2],[1],[0.5]],dtype='float')
b = 0.01
a = tf.linalg.matmul(weights,features) + b
print(a)
p = tf.sigmoid(a)
print(p.numpy()[0][0])

tf.Tensor([[0.51]], shape=(1, 1), dtype=float32)
0.62480646
